### ISSUE TITLE
Add starpatten in your programing language

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#2]
Make your own folder name it your programing language, and make starpattern file. Example output if given n is 5:
```
* 
* * 
* * *
* * * *
* * * * *
```
More example you can look at starpattern.js at src/javascript

**Comment by Aman-kulshreshtha** [comment]
i will do it

**Comment by explise** [comment]
i can do it in c++

**Comment by Reynadi531** [comment]
go ahead

**Comment by DipanNama** [comment]
I can do this in C
Should I do this

**Comment by Halix267** [comment]
I will do it in java. Can i do this

**Comment by Reynadi531** [comment]
Sure, go ahead
