### ISSUE TITLE
Add arrow buttom left pattern

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#3]
# Hey i want to have patterns like this:
```
*       * 
* *   *   
* * *     
* * * *   
* * * * * 
```
- Do it in your favorite programing language, remember to ask for assign this issue.
- If your favorit language folder doesn't exist, make it by your self and add file name it arrow-button-left
- Don't forget to test and check your PR

**Comment by Halix267** [comment]
Hey @Reynadi531 . I want to work on this issue

**Comment by Reynadi531** [comment]
sure, go ahead

**Comment by Halix267** [comment]
I have to write code only for n=5 or n can be greater than 5?

**Comment by Reynadi531** [comment]
No problem, please comment that issue at the end of your solution

**Comment by Aman-kulshreshtha** [comment]
i want to have this

**Comment by Reynadi531** [comment]
yes you can do it in your favorite language

**Comment by fredy-rusty** [comment]
i add the code :)

**Comment by flribeiro** [comment]
Give it to me

**Comment by karshil2309** [comment]
Hey there, I would like to contribute. I will do it in java. Pls assign.

**Comment by Reynadi531** [comment]
Yeah everyone go ahead

**Comment by Reynadi531** [comment]
Thanks for contribute everyone
