### ISSUE TITLE
Add hollow triangle pattern

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#34]
# Hey i want to have patterns like this:
```
* 
* * 
*   * 
*     * 
* * * * *
 ```
- Do it in your favorite programing language, remember to ask for assign this issue.
- Make sure it's dynamic meaning your pattern can easily resized just by change a variable
- If your favorit language folder doesn't exist, make it by your self and add file name it hollowtrianglepatternby[your name]
- Don't forget to test and check your PR

## Rules:
- ### Do not overwrite other people file 
- ### This is not about who the fast but is about writing a beautiful code
- ### Comment the output of your code at the end of file
- ### Add yourself to README.md

**Comment by salonigoyal2309** [comment]
@Reynadi531 i can work on this :)

**Comment by ymchandaliya** [comment]
@Reynadi531 I would like to contribute. Please assign me this task.
I can implement in C, C++, Java, Python.

**Comment by ruthwik3690** [comment]
@Reynadi531 I am ready to do this. Please let me in.

**Comment by Reynadi531** [comment]
OK everyone go ahead

**Comment by AbenezerKb** [comment]
let me in!

**Comment by Reynadi531** [comment]
sure

**Comment by RishabhPathak1211** [comment]
@Reynadi531 I would like to work on this

**Comment by Abantika20** [comment]
Please assign it to me. I wish to do it in C.

**Comment by hungpv-2151** [comment]
Please assign it to me.

I will do it with javascript

**Comment by ymchandaliya** [comment]
feat : Add hollow triangle pattern @Reynadi531 #41

**Comment by helara** [comment]
I would like to contribute! Can do it in Java.

**Comment by Reynadi531** [comment]
Go ahead everyone

**Comment by ymchandaliya** [comment]
Changes made as per your suggestion
Add Hollow Triangle pattern @Reynadi531  #41

**Comment by ayush-git228** [comment]
I would be happy to contribute (in c++).

**Comment by rohan8660** [comment]
Can I try this ? Please.

**Comment by 770grappenmaker** [comment]
I can make some patterns, also triangles in java and javascript, can you assign me?

**Comment by rohan8660** [comment]
I did it !! Please check #51

**Comment by rohan8660** [comment]
Thanks for the opportunity.

**Comment by ShubhamNagure** [comment]
This will be my first contribution If you assign me. ;)

**Comment by mk1107** [comment]
I can perform task in c, cpp, python language.
please assign me to do task.

**Comment by ashish-garg18** [comment]
I would like to contribute. Assign me this task.
I can implement in C, C++, Java, Python.

**Comment by Reynadi531** [comment]
limitation of people who can be assigned is just 10. Maybe you can try on another issue

**Comment by ashish-garg18** [comment]
@Reynadi531 In Which language should I work?

**Comment by Reynadi531** [comment]
> @Reynadi531 In Which language should I work?

Your favorite language

**Comment by mk1107** [comment]
> limitation of people who can be assigned is just 10. Maybe you can try on another issue

can you please add me also as I have asked first.

**Comment by ChaosEx** [comment]
Assign me
