### ISSUE TITLE
Add diamond pattern

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#4]
# Hey i want to have patterns like this:
```
        * 
      * * * 
    * * * * * 
  * * * * * * * 
* * * * * * * * * 
  * * * * * * * 
    * * * * * 
      * * * 
        *
 ```
- Do it in your favorite programing language, remember to ask for assign this issue.
- Make sure it's dynamic meaning you have a horizontal and vertical value that changeable
- If your favorit language folder doesn't exist, make it by your self and add file name it diamondpattern
- Don't forget to test and check your PR

**Comment by kavyamehra20** [comment]
Please assign me this issue.

**Comment by Reynadi531** [comment]
sure, go ahead

**Comment by nishantbhadke** [comment]
> # Hey i want to have patterns like this:
> ```
>         * 
>       * * * 
>     * * * * * 
>   * * * * * * * 
> * * * * * * * * * 
>   * * * * * * * 
>     * * * * * 
>       * * * 
>         *
> ```
> 
> * Do it in your favorite programing language, remember to ask for assign this issue.
> * Make sure it's dynamic meaning you have a horizontal and vertical value that changeable
> * If your favorit language folder doesn't exist, make it by your self and add file name it diamondpattern
> * Don't forget to test and check your PR

`python code for this Diamond shape star printing !
#First to define the code for the diamond shape 
#Taken input n, k
def Diamond(rows): 
    m = 0
    for i in range(1, rows + 1): 
        # loop to print spaces 
        for j in range (1, (rows - i) + 1): 
            print(end = " ") 
          
        # 1st upper for loop to print star 
        while m != (2 * i - 1): 
            print("*", end = "") 
            m = m + 1
        m = 0
          
        # line break 
        print()  
  
    k = 1
    m = 1
    for i in range(1, rows): 
        # For loop to print spaces 
        for j in range (1, k + 1): 
            print(end = " ") 
        k = k + 1
          
        # 2nd lower For loop to print star 
        while m <= (2 * (rows - i) - 1): 
            print("*", end = "") 
            m = m + 1
        m = 1
        print() 
  
# Driver Code 
# Assigning number of rows input 
rows = 5
Diamond(rows)'

**Comment by vczoika** [comment]
Hey, can I do it in Java?

**Comment by Reynadi531** [comment]
@nishantbhadke you can make a python folder and make file name it diamondpattern.py

**Comment by Reynadi531** [comment]
@vczoika sure, go ahead

**Comment by nishantbhadke** [comment]
i am currently new to git and starting to learn

**Comment by kdimas12** [comment]
hii, can I do it in C++ ?

**Comment by Dilpreet047** [comment]
Please assign this issue to me.

**Comment by kavyamehra20** [comment]
import java.util.Scanner;
public class diamondpattern {
public static void main(String[] args){
   int i,j,h;
   System.out.print("Input number of rows of half of the diamond : ");
   Scanner sc = new Scanner(System.in);
   h = sc.nextInt();
   for(i=0;i<=h;i++){
     for(j=1;j<=h-i;j++)
     System.out.print(" ");
     for(j=1;j<=2*i-1;j++)
       System.out.print("*");
     System.out.print("  ");
   }
 
   for(i=h-1;i>=1;i--) {
     for(j=1;j<=h-i;j++)
     System.out.print(" ");
     for(j=1;j<=2*i-1;j++)
       System.out.print("*");
     System.out.print("   ");
   }
}
}

**Comment by nishantbhadke** [comment]
> Hey, can I do it in Java?

i will try to do 
import java.util.*; 
  
class Diamonds
{ 
      
    // Prints diamond pattern 
    // with 2n rows 
    static void printDiamond(int n) 
    { 
        int space = n - 1; 
      
        // running the loop (parent loop)  
        // till number of rows 
        for (int i = 0; i < n; i++) 
        { 
            // loop for initially space,  
            // Thus before star printing 
            for (int j = 0; j < space; j++) 
                System.out.print(" "); 
      
            // Printing i+1 stars 
            for (int j = 0; j <= i; j++) 
                System.out.print("* "); 
      
            System.out.print("\n"); 
            space--; 
        } 
      
        // Repeat again in 
        // reverse order 
        space = 0; 
      
        // run loop (parent loop)  
        // till number of rows 
        for (int i = n; i > 0; i--) 
        { 
            // loop for initially space,  
            // before star printing 
            for (int j = 0; j < space; j++) 
                System.out.print(" "); 
      
            // Print i stars 
            for (int j = 0; j < i; j++) 
                System.out.print("* "); 
      
            System.out.print("\n"); 
            space++; 
        } 
    } 
      
    // Driver Code 
    public static void main(String[] args)  
    { 
        printDiamond(5); 
          
    } 
}

**Comment by Reynadi531** [comment]
Everyone please make a PR not comment a code on this issues

**Comment by crazyvibes** [comment]
Hi can you assign me? I will use java to make this pattern.

**Comment by kavyamehra20** [comment]
Please check

**Comment by Reynadi531** [comment]
Do it in src/your favorite language

**Comment by rohan8660** [comment]
I want to do the same, Can I get assigned please ? I can do it in C and Python and I can try in web (using JavaScript)

**Comment by rohan8660** [comment]
I did it in C, thanks. Please check out #52

**Comment by ShubhamNagure** [comment]
Please assign me this.

**Comment by ChaosEx** [comment]
Assign me
