### ISSUE TITLE
Add a hollowsquare pattern

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#5]
# Hey i want to have patterns like this:
```   
* * * * * 
*       * 
*       * 
*       * 
* * * * * 
 ```
- Do it in your favorite programing language, remember to ask for assign this issue.
- Make sure it's dynamic meaning you have a horizontal and vertical value that changeable
- If your favorit language folder doesn't exist, make it by yourself and add file, name it hollowsquarepattern
- Don't forget to test and check your PR

**Comment by DeltaHarbinger** [comment]
Hey @Reynadi531, can you assign this to me?

**Comment by tusshar17** [comment]
@Reynadi531 Please assign me for this.

**Comment by NidhiNivedita6** [comment]
Please assign me this.

**Comment by Reynadi531** [comment]
sure everyone, go ahead

**Comment by Mayankjha997** [comment]
hey! i want to contribute in this repo in c language

**Comment by ShubhamNagure** [comment]
Hi @Reynadi531 ,

Please assign me.

Thanks

**Comment by nakennedy11** [comment]
Hello,

I have a Java solution for the hollowsquare, if it's still open I'd like to be assigned. 

Thanks!

**Comment by Reynadi531** [comment]
Yeah, go ahead

**Comment by darshmgandhi** [comment]
@Reynadi531 I want to contribute in python. Please assign me for this issue.

**Comment by i-am-shashank** [comment]
i have a solution in javascript, shall i go ahed!

**Comment by ChaosEx** [comment]
Assign me
