### ISSUE TITLE
Add square pattern

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#6]
# Hey i want to have patterns like this:
```
* * * * * 
* * * * * 
* * * * * 
* * * * * 
* * * * * 
 ```
- Do it in your favorite programing language, remember to ask for assign this issue.
- Make sure it's dynamic meaning you can change the size of it
- If your favorit language folder doesn't exist, make it by your self and add file name it diamondpattern
- Don't forget to test and check your PR

**Comment by Aravindha1234u** [comment]
Can you assign this to me.

**Comment by tusshar17** [comment]
please assign me for this.

**Comment by i-am-shashank** [comment]
hey, can i try this one!

**Comment by Halix267** [comment]
Can I work on this

**Comment by Reynadi531** [comment]
yup everyone, go ahead

**Comment by DriftingShadows** [comment]
If there's room id like to give it a go.

**Comment by Reynadi531** [comment]
sure

**Comment by David-Lazaro-Fernandez** [comment]
### Hi ! 
If there's room. I'd like to do it!

**Comment by ruthwik3690** [comment]
I would like to do, please assign me!

**Comment by DhanushNehru** [comment]
> # Hey i want to have patterns like this:
> ```
> * * * * * 
> * * * * * 
> * * * * * 
> * * * * * 
> * * * * * 
> ```
> 
> * Do it in your favorite programing language, remember to ask for assign this issue.
> * Make sure it's dynamic meaning you can change the size of it
> * If your favorit language folder doesn't exist, make it by your self and add file name it diamondpattern
> * Don't forget to test and check your PR

Can you assign this to me ?

**Comment by hungpv-2151** [comment]
May I join?

**Comment by kots14** [comment]
May send a pull request for this using Java?

**Comment by ShubhamNagure** [comment]
Hi @Reynadi531,

May I join you?

Thanks,

**Comment by Reynadi531** [comment]
Sorry guys this issue already hit assignment limitation

**Comment by ChaosEx** [comment]
Assign me
