### ISSUE TITLE
Diamond star pattern

### ISSUE THREAD

**Issue by Halix267** [Reynadi531/a-patterns#67]
![diamond](https://user-images.githubusercontent.com/63572018/95230656-c6f6bf00-081f-11eb-801b-fa4ec90d5704.png)

**Comment by Halix267** [comment]
Hey @Reynadi531 .Can i work on this issue

**Comment by Reynadi531** [comment]
Hey, why did you make a new issue?

**Comment by Reynadi531** [comment]
Do it in another issues that labeled hacktoberfest
