### ISSUE TITLE
Triangle Star Pattern

### ISSUE THREAD

**Issue by Vrindagupta6828** [Reynadi531/a-patterns#68]
![p](https://user-images.githubusercontent.com/50476758/95237853-57380280-0826-11eb-819c-fbf855d1e221.png)

**Comment by Vrindagupta6828** [comment]
@Reynadi531 hey can i please work on this issue

**Comment by Reynadi531** [comment]
Hey, why did you make a new issue? Do it in another issues where it labeled hacktoberfest
