### ISSUE TITLE
Diamond Numeric Pattern

### ISSUE THREAD

**Issue by Vrindagupta6828** [Reynadi531/a-patterns#69]
![p2](https://user-images.githubusercontent.com/50476758/95238602-5ce21800-0827-11eb-9aa6-d56e8d91f0ac.png)

**Comment by Vrindagupta6828** [comment]
@Reynadi531 Hey can i work on this issue?

**Comment by Reynadi531** [comment]
Do it in another issues labeled hacktoberfest
