### ISSUE TITLE
Make numbers triangle

### ISSUE THREAD

**Issue by Reynadi531** [Reynadi531/a-patterns#72]
# Hey i want to have patterns like this:
```
1 2 3 4 5
1 2 3 4
1 2 3
1 2
1
 ```
- Do it in your favorite programing language, remember to ask for assign this issue.
- Make sure it's dynamic meaning your pattern can easily resized just by change a variable
- If your favorit language folder doesn't exist, make it by your self and add file name it hollowtrianglepatternby[your name]
- Don't forget to test and check your PR

## Rules:
- ### Do not overwrite other people file 
- ### This is not about who the fast but is about writing a beautiful code
- ### Comment the output of your code at the end of file
- ### Add yourself to README.md

**Comment by Thoutan1** [comment]
Only specify language or all languages?

**Comment by Reynadi531** [comment]
> Only specify language or all languages?

All languages accepted

**Comment by rishiraj52** [comment]
Can you assign this t me @Reynadi531 ?

**Comment by Reynadi531** [comment]
> Can you assign this t me @Reynadi531 ?

Done, happy coding

**Comment by AnkurRajneta** [comment]
I am interested.Can you assign me this.

**Comment by Reynadi531** [comment]
> I am interested.Can you assign me this.

Sure

**Comment by rishiraj52** [comment]
I've added the file, please do merge and label it if you like my work.
Thanks!

**Comment by surajondev** [comment]
Hey, I want to create a number triangle pattern in JS

It will look like this:

1
12
123
1234
12345

So assign me for the job

**Comment by Reynadi531** [comment]
> Hey, I want to create a number triangle pattern in JS
> 
> It will look like this:
> 
> 1 12 123 1234 12345
> 
> So assign me for the job

Ok go ahead

**Comment by SorataBaka** [comment]
Hi, id like to create one with C. can you assign this to me?

**Comment by Reynadi531** [comment]
> Hi, id like to create one with C. can you assign this to me?

Sure go ahead

**Comment by Reynadi531** [comment]
Glad to see you all working. See you in another days
